# This workflow will build a Java project


name: java CI with Gradle                #optional

on:                                      #name of event that triggers the workflow
  push:
     branches: [ master]
  pull_request:    
     branches: [master]

jobs:                                     # set of tasks(steps)
  build-java:

     runs-on: ubuntu-latest 
       
     steps:                               #steps can run commands, setup tasks or run an action
     - uses: actions/checkout@v4      
        
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1        #select an action
       with:
         java-versions: 1.8
     
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew              #run commands

     - name: Build with Gradle
       run: ./gradlew build        

     - name: Build and push Docker Image
       uses: mr-smithers-excellent/docker-build-push@v4
       with:
         image: niyi1983/githubactions
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
